server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/rental-api
          jwk-set-uri: http://localhost:8081/auth/realms/rental-api/protocol/openid-connect/certs


